### ISSUE TITLE
Api are probably changed

### ISSUE THREAD

**Issue by NicKoehler** [clarkd/fordpass-python#6]
Using the provided demo.py script, I receive this error in response:

```
Traceback (most recent call last):
  File "/home/nic/Scrivania/./demo.py", line 17, in <module>
    print(r.status()) # Print the status of the car
  File "/home/nic/Scrivania/venv/lib/python3.10/site-packages/fordpass/fordpass.py", line 86, in status
    r.raise_for_status()
  File "/home/nic/Scrivania/venv/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://usapi.cv.ford.com/api/vehicles/v4/###########/status?lrdt=01-01-1970+00%3A00%3A00

```

**Comment by jlanglois65** [comment]
This is the error message when pasting the url in a browser:

{ "statusCode": 401, "message": "Access denied due to missing subscription key. Make sure to include subscription key when making requests to an API." }

**Comment by cddu33** [comment]
Hello,

I have the same problem and I use the subscription key correctly.
I was using this script for 2 months with no issues and since January the same error

I am in France

**Comment by NicKoehler** [comment]
try my fork [here](https://github.com/NicKoehler/fordpass-python)
